use_frameworks!

platform :ios, '11.0'

target 'LATableBuilder_Example' do
  pod 'LATableBuilder', :path => '../'

  target 'LATableBuilder_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble', '~> 9.2'
    pod 'FBSnapshotTestCase'
  end
end
